Repository bizbuzim/bizbuzim, pull requests merged in 2022-05, with the labels that each got.

#42 fix(api): stop crashing
  pkg/http/telegram/expense.go
Labels: release-minor

#43 fix(api): stop crashing
  pkg/http/telegram/telegram.go
Labels: release-minor

#45 chore: add logs
  pkg/http/telegram/telegram.go
Labels: release-minor

#46 chore: remove unsupported commands
  pkg/http/telegram/expense.go
  pkg/http/telegram/telegram.go
Labels: release-minor

#48 feat: update welcome message
  pkg/http/telegram/telegram.go
Labels: release-minor

#49 sources 8
  pkg/http/telegram/telegram.go
Labels: release-minor

#50 fix: chat type
  pkg/http/telegram/telegram.go
Labels: release-minor

#51 feat: do not always replay to msg
  pkg/http/telegram/expense.go
  pkg/http/telegram/telegram.go
Labels: release-minor

#52 chore: add logs
  pkg/http/telegram/telegram.go
Labels: release-minor

#53 feat: answer only to groups and supergroup
  pkg/http/telegram/telegram.go
Labels: release-minor

#54 feat(api): support other message parsers
  pkg/http/telegram/default.go
  pkg/http/telegram/default_test.go
  pkg/http/telegram/expense.go
  pkg/http/telegram/parser.go
  pkg/http/telegram/telegram.go
  pkg/http/telegram/with_config_defaults.go
Labels: release-minor

#66 feat(web): use ssl protocol
  web/src/config.ts
Labels: release-minor

#67 fix(web): update hasura port
  web/Dockerfile
Labels: release-minor

#69 feat(web): add values panel
  web/src/views/home.tsx
Labels: release-minor

#70 feat(web): update default value, replace date lib
  web/package.json
  web/src/App.tsx
  web/src/components/date-picker.tsx
  web/src/context/filters.ts
  web/src/views/filters.tsx
  web/src/views/home.tsx
  web/yarn.lock
Labels: release-minor

#71 feat(web): align ux
  web/src/views/expenses/index.tsx
  web/src/views/expenses/styles.tsx
  web/src/views/expenses/table.tsx
Labels: release-minor

#86 ui fixes
  web/src/App.tsx
  web/src/components/charts/container.tsx
  web/src/views/expenses/index.tsx
  web/src/views/filters.tsx
  web/src/views/home.tsx
Labels: release-minor

#87 fix(ci): job ouput
  .github/workflows/release.yaml
Labels: release-minor

#89 chore(ci): update script
  .github/workflows/release.yaml
Labels: release-minor

#90 fix(ci): update prepare job
  .github/workflows/release.yaml
Labels: release-minor

#91 fix(ci): login to github
  .github/workflows/release.yaml
Labels: release-minor

#95 feat: pass time diff as args
  web/src/views/expenses/date.tsx
Labels: release-minor

#100 fix: resolve conflict
  web/src/components/charts/line.tsx
Labels: release-patch

#105 fix date calculate
  web/src/views/expenses/__tests__/age.test.ts
  web/src/views/expenses/age.ts
  web/src/views/expenses/date.tsx
Labels: release-minor, bug-fix

#107 fix: docs ci
  .github/workflows/docs.yaml
  .gitignore
  .gitmodules
  docs/config.yaml
  docs/public/404.html
  docs/public/categories/index.html
  docs/public/categories/index.xml
  docs/public/contribute/index.html
  docs/public/contribute/index.xml
  docs/public/deploy/index.html
  docs/public/deploy/index.xml
  docs/public/index.html
  docs/public/index.json
  docs/public/index.xml
  docs/public/sitemap.xml
  docs/public/tags/index.html
  docs/public/tags/index.xml
Labels: release-minor

#109 docs: add content
  .gitignore
  docs/content/_index.md
  docs/content/console-charts.png
  docs/content/console-table.png
Labels: release-minor
